### ISSUE TITLE
Page share link wrong

### ISSUE THREAD

**Issue by majianming21** [recurser/string-is#1217]
## Current behavior
hello ,i setup string-is with docker,and set a env value for NEXT_PUBLIC_ANALYTICS_DOMAIN AS mydomain.xyz ,when i use share button,it always copy to clipboard as http://localhost:3000/json-formatter?i=xxxx
what is worng ?,
i guest process.env.NEXT_PUBLIC_ANALYTICS_DOMAIN  can't compile to  a sure value when dockerfile build. 
in my domain with docker
![ my domain with docker js](https://github.com/recurser/string-is/assets/18475632/ff718e0f-2dbf-4e0d-af88-d1f7fab80e82)
in https://string.is/
![string.is is](https://github.com/recurser/string-is/assets/18475632/8fdb4e39-46e4-463f-af87-9d36845f6d95)

## Environment
docker image daveperrett/string-is:v1.35.1

**Comment by recurser** [comment]
@majianming21 thanks reporting this, and apologies for the delay. Fixed in [v1.37.0](https://github.com/recurser/string-is/releases/tag/v1.37.0).
