### ISSUE TITLE
Exec format error in arm64 docker images

### ISSUE THREAD

**Issue by HellLord77** [recurser/string-is#1288]
all the docker image builds of arm64 are currently failing (exec format error, trying to run amd64 image in arm64)
the images are wrongly built due to an error in Dockerfile

my guess is fixing [this line](https://github.com/recurser/string-is/blob/f48ea51ce0b06c53c78f2f598666a1b435b76412/Dockerfile#L21) should address the problem

`FROM --platform=$TARGETPLATFORM node:20-alpine AS runner`

$BUILDPLATFORM is currently amd64 (64-bit runners of github), so amd64 builds are working as intended
$TARGETPLATFORM in target stage should correctly target for cross builds

## Environment

- **string-is** version: daveperrett/string-is:* [all the existing arm64 images]

**Comment by recurser** [comment]
D'oh - thanks for the heads-up @HellLord77 !

Are you able to provide steps to reproduce? If I run this on an M1 Mac it works as expected:

`docker run --platform linux/arm64 -p 3000:3000 daveperrett/string-is:v1.35.3`

I'd just like to be able to reproduce it so I'll know that it's fixed by the Dockerfile change you suggested. Thanks!

**Comment by HellLord77** [comment]
Thanks for looking into the issue, and for the amazing tool!

Running the suggested 'docker run' throws the following error in my arm64 (Orange Pi 5, 4GB), imm

```exec /usr/local/bin/docker-entrypoint.sh: exec format error```

Let me try building the image and checking if it works as expected or if something else is the culprit.

**Comment by recurser** [comment]
@HellLord77 I've made that change in [v1.35.4](https://github.com/recurser/string-is/releases/tag/v1.35.4), and it seems to work for me here. Thanks for the heads-up, and feel free to re-open this if you have any further problems!
