### ISSUE TITLE
Link for Plausible Analytics on Security page is incorrect

### ISSUE THREAD

**Issue by staceybellerose** [recurser/string-is#1328]
## Current behavior

On the Security page, the link for Plausible Analytics links to https://letsencrypt.org/

## Expected behavior

The link should be to their home page https://plausible.io/

## Environment

- **string-is** version: live site
- Share link: https://string.is/security

**Comment by staceybellerose** [comment]
Error in source can be found at https://github.com/recurser/string-is/blob/efdd4148ef1e19bb16ffa4e1446edffcae7cb0ec/src/components/pages/Security.tsx#L82

**Comment by recurser** [comment]
@staceybellerose good catch - thanks! Fixed in [v1.37.2](https://github.com/recurser/string-is/releases/tag/v1.37.2)
